### ISSUE TITLE
PhotoController

### ISSUE THREAD

**Issue by lnl775** [manufarfaro/musichub-api#2]
No se puede eliminar una foto de artista o banda siempre se obtiene Page Not Found (404) aunque el elemento a eliminar exista en la BBDD.

**Comment by manufarfaro** [comment]
@lnl775 ¡Gracias! Ya deberías poder eliminar tanto las fotos del usuario como de las bandas que te pertenezcan (bajo el rol de líder únicamente por ahora). Recordá que como bien documenta el código el acto de borrar una foto solo es afectado sobre el perfil del usuario que lo elimína (no se borra la foto sinó que se borra la relación con el artista por una cuestión de coherencia con lo hasta ahora desarrollado)
Si podés volver a chequear y comentarme si te funciona te lo agradecería.
Saludos.

**Comment by lnl775** [comment]
@manufarfaro listo!!! ya funciona la eliminación (borrado de la relación)
Gracias.
