### ISSUE TITLE
ProfileController

### ISSUE THREAD

**Issue by lnl775** [manufarfaro/musichub-api#3]
Se ha detectado un error 500 en el ProfileController al utilizar el PUT method con el parametro birthdate con el valor 1991-05-01T04:00:00Z

![image](https://cloud.githubusercontent.com/assets/7862104/8975638/fc9ec53e-3657-11e5-9abc-52d2a8f98d1e.png)

**Comment by manufarfaro** [comment]
@lnl775 ahi acabo de subir el fix de la funcionalidad, el formato correcto de entrada es **dd/MM/yyyy**, se atrapó la excepcion ParseException que tiraba el error 500.

¡Gracias! :+1:

**Comment by lnl775** [comment]
@manufarfaro si bien el error 500 desaparecio todavia sigue sin actualizar el campo birthdate
PostMan
![image](https://cloud.githubusercontent.com/assets/7862104/8998911/7565cc2c-3709-11e5-84e9-fc1dcb63bc63.png)
Postgresql
![image](https://cloud.githubusercontent.com/assets/7862104/8998934/a08c6a28-3709-11e5-8726-1f7bdd2f852a.png)

**Comment by manufarfaro** [comment]
@lnl775 El formato para la fecha de nacimiento es: **dd/MM/yyyy**, veo que estas usando**-** en vez de **/**, a continuación como lo estoy haciendo yo:

![selection_002](https://cloud.githubusercontent.com/assets/908703/9007113/97175330-3764-11e5-9e53-6caceff3186a.png)

Confirmame si de esta manera podés editarlo y si es así avisame así cierro el issue.

¡Gracias! :smile:

**Comment by lnl775** [comment]
@manufarfaro Tenias razón!!!...eso me pasa por copiar el formato de la fecha de la bbdd :P
Confirmado funciona OK!!!
