### ISSUE TITLE
DiscsController

### ISSUE THREAD

**Issue by lnl775** [manufarfaro/musichub-api#4]
Al querer realizar el alta de un disco para la banda divididos se producieron inconsistencias al generar el mismo en la tabla disc.
Al invocar el DiscsController con los parametros necesarios name (Narigon del siglo) y como usuario ricardo.mollo (lider de la banda divididos) en el authorization al ejecutar el metodo POST se obtuvo

![image](https://cloud.githubusercontent.com/assets/7862104/9008391/74bdf4c2-3770-11e5-9bdc-9517afd7e23a.png)

Como se puede observar los campos artist_id y band_id quedan con valores null esto produce que no quede asociado el disco a la banda que corresponde.

Nota: Por cuestiones de testing se volvió a invocar el mismo método con los mismos parámetros para tratar de ver el error por esa razón hay 2 registros iguales.

**Comment by manufarfaro** [comment]
El issue ya se encuentra resuelto en 5c0e6d561eb27bd400740e2119e5100e5b990817.
Gracias!
